version: '3.8'

services:
  web:
    build:
      dockerfile: ./docker/Dockerfile_web
      context: ./..
    ports:
      - "8000:8000"
    tty: true
    command: sh -c "gunicorn ghibli_app.asgi:application -k uvicorn.workers.UvicornWorker -b 0.0.0.0:8000"

  cache:
    build:
      dockerfile: ./docker/Dockerfile_cache
      context: ./..
    depends_on:
      - web
    restart: always
    expose:
      - "11211"
    command: sh -c "memcached -u nobody -p 11211"
